//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosSalida.buzone.ordenescompra
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://services.ws.promass.buzone.com/", ConfigurationName = "buzone.ordenescompra.OrdenCompraService")]
    public interface OrdenCompraService
    {

        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "urn:InsertOrdenCompra", ReplyAction = "http://services.ws.promass.buzone.com/OrdenCompraService/insertOrdenCompraRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        ServiciosSalida.buzone.ordenescompra.insertOrdenCompraResponse insertOrdenCompra(ServiciosSalida.buzone.ordenescompra.insertOrdenCompraRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "urn:InsertOrdenCompra", ReplyAction = "http://services.ws.promass.buzone.com/OrdenCompraService/insertOrdenCompraRespons" +
            "e")]
        System.Threading.Tasks.Task<ServiciosSalida.buzone.ordenescompra.insertOrdenCompraResponse> insertOrdenCompraAsync(ServiciosSalida.buzone.ordenescompra.insertOrdenCompraRequest request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://services.ws.promass.buzone.com/")]
    public partial class ordenCompra : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string userField;

        private string passwordField;

        private string codigoSNField;

        private string rfcProveedorField;

        private string rfcReceptorField;

        private int docEntryField;

        private string casField;

        private string folioRecepcionField;

        private string codigoMonedaField;

        private decimal subTotalField;

        private decimal impuestoRetenidoField;

        private decimal impuestoTrasladadoField;

        private decimal totalField;

        private decimal descuentoField;

        private decimal tipoCambioField;

        private string formaPagoField;

        private string metodoPagoField;

        private string tipoComprobanteField;

        private string condicionesPagoField;

        private string usoCFDIField;

        private string accionField;

        private string activoField;

        private linea[] lineasField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string user
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string codigoSN
        {
            get
            {
                return this.codigoSNField;
            }
            set
            {
                this.codigoSNField = value;
                this.RaisePropertyChanged("codigoSN");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string rfcProveedor
        {
            get
            {
                return this.rfcProveedorField;
            }
            set
            {
                this.rfcProveedorField = value;
                this.RaisePropertyChanged("rfcProveedor");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string rfcReceptor
        {
            get
            {
                return this.rfcReceptorField;
            }
            set
            {
                this.rfcReceptorField = value;
                this.RaisePropertyChanged("rfcReceptor");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public int docEntry
        {
            get
            {
                return this.docEntryField;
            }
            set
            {
                this.docEntryField = value;
                this.RaisePropertyChanged("docEntry");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public string cas
        {
            get
            {
                return this.casField;
            }
            set
            {
                this.casField = value;
                this.RaisePropertyChanged("cas");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public string folioRecepcion
        {
            get
            {
                return this.folioRecepcionField;
            }
            set
            {
                this.folioRecepcionField = value;
                this.RaisePropertyChanged("folioRecepcion");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
        public string codigoMoneda
        {
            get
            {
                return this.codigoMonedaField;
            }
            set
            {
                this.codigoMonedaField = value;
                this.RaisePropertyChanged("codigoMoneda");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 9)]
        public decimal subTotal
        {
            get
            {
                return this.subTotalField;
            }
            set
            {
                this.subTotalField = value;
                this.RaisePropertyChanged("subTotal");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 10)]
        public decimal impuestoRetenido
        {
            get
            {
                return this.impuestoRetenidoField;
            }
            set
            {
                this.impuestoRetenidoField = value;
                this.RaisePropertyChanged("impuestoRetenido");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 11)]
        public decimal impuestoTrasladado
        {
            get
            {
                return this.impuestoTrasladadoField;
            }
            set
            {
                this.impuestoTrasladadoField = value;
                this.RaisePropertyChanged("impuestoTrasladado");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 12)]
        public decimal total
        {
            get
            {
                return this.totalField;
            }
            set
            {
                this.totalField = value;
                this.RaisePropertyChanged("total");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 13)]
        public decimal descuento
        {
            get
            {
                return this.descuentoField;
            }
            set
            {
                this.descuentoField = value;
                this.RaisePropertyChanged("descuento");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 14)]
        public decimal tipoCambio
        {
            get
            {
                return this.tipoCambioField;
            }
            set
            {
                this.tipoCambioField = value;
                this.RaisePropertyChanged("tipoCambio");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 15)]
        public string formaPago
        {
            get
            {
                return this.formaPagoField;
            }
            set
            {
                this.formaPagoField = value;
                this.RaisePropertyChanged("formaPago");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 16)]
        public string metodoPago
        {
            get
            {
                return this.metodoPagoField;
            }
            set
            {
                this.metodoPagoField = value;
                this.RaisePropertyChanged("metodoPago");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 17)]
        public string tipoComprobante
        {
            get
            {
                return this.tipoComprobanteField;
            }
            set
            {
                this.tipoComprobanteField = value;
                this.RaisePropertyChanged("tipoComprobante");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 18)]
        public string condicionesPago
        {
            get
            {
                return this.condicionesPagoField;
            }
            set
            {
                this.condicionesPagoField = value;
                this.RaisePropertyChanged("condicionesPago");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 19)]
        public string usoCFDI
        {
            get
            {
                return this.usoCFDIField;
            }
            set
            {
                this.usoCFDIField = value;
                this.RaisePropertyChanged("usoCFDI");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 20)]
        public string accion
        {
            get
            {
                return this.accionField;
            }
            set
            {
                this.accionField = value;
                this.RaisePropertyChanged("accion");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 21)]
        public string activo
        {
            get
            {
                return this.activoField;
            }
            set
            {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("lineas", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 22)]
        public linea[] lineas
        {
            get
            {
                return this.lineasField;
            }
            set
            {
                this.lineasField = value;
                this.RaisePropertyChanged("lineas");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://services.ws.promass.buzone.com/")]
    public partial class linea : object, System.ComponentModel.INotifyPropertyChanged
    {

        private int linea1Field;

        private string descripcionField;

        private decimal importeField;

        private string codigoArticuloField;

        private decimal cantidadArticulosField;

        private string claveUnidadField;

        private decimal precioField;

        private decimal descuentoField;

        private string unidadField;

        private string noIdentificacionField;

        private string noCuentaPredialField;

        private string cveProductoField;

        private impuestosTrasladados impuestosTrasladadosField;

        private impuestosRetenidos impuestosRetenidosField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("linea", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public int linea1
        {
            get
            {
                return this.linea1Field;
            }
            set
            {
                this.linea1Field = value;
                this.RaisePropertyChanged("linea1");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public decimal importe
        {
            get
            {
                return this.importeField;
            }
            set
            {
                this.importeField = value;
                this.RaisePropertyChanged("importe");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string codigoArticulo
        {
            get
            {
                return this.codigoArticuloField;
            }
            set
            {
                this.codigoArticuloField = value;
                this.RaisePropertyChanged("codigoArticulo");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public decimal cantidadArticulos
        {
            get
            {
                return this.cantidadArticulosField;
            }
            set
            {
                this.cantidadArticulosField = value;
                this.RaisePropertyChanged("cantidadArticulos");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public string claveUnidad
        {
            get
            {
                return this.claveUnidadField;
            }
            set
            {
                this.claveUnidadField = value;
                this.RaisePropertyChanged("claveUnidad");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public decimal precio
        {
            get
            {
                return this.precioField;
            }
            set
            {
                this.precioField = value;
                this.RaisePropertyChanged("precio");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public decimal descuento
        {
            get
            {
                return this.descuentoField;
            }
            set
            {
                this.descuentoField = value;
                this.RaisePropertyChanged("descuento");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
        public string unidad
        {
            get
            {
                return this.unidadField;
            }
            set
            {
                this.unidadField = value;
                this.RaisePropertyChanged("unidad");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 9)]
        public string noIdentificacion
        {
            get
            {
                return this.noIdentificacionField;
            }
            set
            {
                this.noIdentificacionField = value;
                this.RaisePropertyChanged("noIdentificacion");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 10)]
        public string noCuentaPredial
        {
            get
            {
                return this.noCuentaPredialField;
            }
            set
            {
                this.noCuentaPredialField = value;
                this.RaisePropertyChanged("noCuentaPredial");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 11)]
        public string cveProducto
        {
            get
            {
                return this.cveProductoField;
            }
            set
            {
                this.cveProductoField = value;
                this.RaisePropertyChanged("cveProducto");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 12)]
        public impuestosTrasladados impuestosTrasladados
        {
            get
            {
                return this.impuestosTrasladadosField;
            }
            set
            {
                this.impuestosTrasladadosField = value;
                this.RaisePropertyChanged("impuestosTrasladados");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 13)]
        public impuestosRetenidos impuestosRetenidos
        {
            get
            {
                return this.impuestosRetenidosField;
            }
            set
            {
                this.impuestosRetenidosField = value;
                this.RaisePropertyChanged("impuestosRetenidos");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://services.ws.promass.buzone.com/")]
    public partial class impuestosTrasladados : object, System.ComponentModel.INotifyPropertyChanged
    {

        private iva[] listaIVAField;

        private ieps[] listaIEPSField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("IVA", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public iva[] listaIVA
        {
            get
            {
                return this.listaIVAField;
            }
            set
            {
                this.listaIVAField = value;
                this.RaisePropertyChanged("listaIVA");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("IEPS", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public ieps[] listaIEPS
        {
            get
            {
                return this.listaIEPSField;
            }
            set
            {
                this.listaIEPSField = value;
                this.RaisePropertyChanged("listaIEPS");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://services.ws.promass.buzone.com/")]
    public partial class iva : object, System.ComponentModel.INotifyPropertyChanged
    {

        private int numeroImpuestoField;

        private decimal baseField;

        private string impuestoField;

        private string tipoFactorField;

        private decimal tasaField;

        private decimal importeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public int numeroImpuesto
        {
            get
            {
                return this.numeroImpuestoField;
            }
            set
            {
                this.numeroImpuestoField = value;
                this.RaisePropertyChanged("numeroImpuesto");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public decimal @base
        {
            get
            {
                return this.baseField;
            }
            set
            {
                this.baseField = value;
                this.RaisePropertyChanged("base");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string impuesto
        {
            get
            {
                return this.impuestoField;
            }
            set
            {
                this.impuestoField = value;
                this.RaisePropertyChanged("impuesto");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string tipoFactor
        {
            get
            {
                return this.tipoFactorField;
            }
            set
            {
                this.tipoFactorField = value;
                this.RaisePropertyChanged("tipoFactor");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public decimal tasa
        {
            get
            {
                return this.tasaField;
            }
            set
            {
                this.tasaField = value;
                this.RaisePropertyChanged("tasa");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public decimal importe
        {
            get
            {
                return this.importeField;
            }
            set
            {
                this.importeField = value;
                this.RaisePropertyChanged("importe");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://services.ws.promass.buzone.com/")]
    public partial class resultado : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string codigoErrorField;

        private string estatusField;

        private string mensajeErrorField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string codigoError
        {
            get
            {
                return this.codigoErrorField;
            }
            set
            {
                this.codigoErrorField = value;
                this.RaisePropertyChanged("codigoError");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string estatus
        {
            get
            {
                return this.estatusField;
            }
            set
            {
                this.estatusField = value;
                this.RaisePropertyChanged("estatus");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string mensajeError
        {
            get
            {
                return this.mensajeErrorField;
            }
            set
            {
                this.mensajeErrorField = value;
                this.RaisePropertyChanged("mensajeError");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://services.ws.promass.buzone.com/")]
    public partial class isr : object, System.ComponentModel.INotifyPropertyChanged
    {

        private int numeroImpuestoField;

        private decimal baseField;

        private string impuestoField;

        private string tipoFactorField;

        private decimal tasaField;

        private decimal importeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public int numeroImpuesto
        {
            get
            {
                return this.numeroImpuestoField;
            }
            set
            {
                this.numeroImpuestoField = value;
                this.RaisePropertyChanged("numeroImpuesto");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public decimal @base
        {
            get
            {
                return this.baseField;
            }
            set
            {
                this.baseField = value;
                this.RaisePropertyChanged("base");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string impuesto
        {
            get
            {
                return this.impuestoField;
            }
            set
            {
                this.impuestoField = value;
                this.RaisePropertyChanged("impuesto");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string tipoFactor
        {
            get
            {
                return this.tipoFactorField;
            }
            set
            {
                this.tipoFactorField = value;
                this.RaisePropertyChanged("tipoFactor");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public decimal tasa
        {
            get
            {
                return this.tasaField;
            }
            set
            {
                this.tasaField = value;
                this.RaisePropertyChanged("tasa");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public decimal importe
        {
            get
            {
                return this.importeField;
            }
            set
            {
                this.importeField = value;
                this.RaisePropertyChanged("importe");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://services.ws.promass.buzone.com/")]
    public partial class impuestosRetenidos : object, System.ComponentModel.INotifyPropertyChanged
    {

        private iva[] listaIVAField;

        private ieps[] listaIEPSField;

        private isr[] listaISRField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("IVA", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public iva[] listaIVA
        {
            get
            {
                return this.listaIVAField;
            }
            set
            {
                this.listaIVAField = value;
                this.RaisePropertyChanged("listaIVA");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("IEPS", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public ieps[] listaIEPS
        {
            get
            {
                return this.listaIEPSField;
            }
            set
            {
                this.listaIEPSField = value;
                this.RaisePropertyChanged("listaIEPS");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ISR", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public isr[] listaISR
        {
            get
            {
                return this.listaISRField;
            }
            set
            {
                this.listaISRField = value;
                this.RaisePropertyChanged("listaISR");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://services.ws.promass.buzone.com/")]
    public partial class ieps : object, System.ComponentModel.INotifyPropertyChanged
    {

        private int numeroImpuestoField;

        private decimal baseField;

        private string impuestoField;

        private string tipoFactorField;

        private decimal tasaField;

        private decimal importeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public int numeroImpuesto
        {
            get
            {
                return this.numeroImpuestoField;
            }
            set
            {
                this.numeroImpuestoField = value;
                this.RaisePropertyChanged("numeroImpuesto");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public decimal @base
        {
            get
            {
                return this.baseField;
            }
            set
            {
                this.baseField = value;
                this.RaisePropertyChanged("base");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string impuesto
        {
            get
            {
                return this.impuestoField;
            }
            set
            {
                this.impuestoField = value;
                this.RaisePropertyChanged("impuesto");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string tipoFactor
        {
            get
            {
                return this.tipoFactorField;
            }
            set
            {
                this.tipoFactorField = value;
                this.RaisePropertyChanged("tipoFactor");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public decimal tasa
        {
            get
            {
                return this.tasaField;
            }
            set
            {
                this.tasaField = value;
                this.RaisePropertyChanged("tasa");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public decimal importe
        {
            get
            {
                return this.importeField;
            }
            set
            {
                this.importeField = value;
                this.RaisePropertyChanged("importe");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "insertOrdenCompra", WrapperNamespace = "http://services.ws.promass.buzone.com/", IsWrapped = true)]
    public partial class insertOrdenCompraRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://services.ws.promass.buzone.com/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiciosSalida.buzone.ordenescompra.ordenCompra oc;

        public insertOrdenCompraRequest()
        {
        }

        public insertOrdenCompraRequest(ServiciosSalida.buzone.ordenescompra.ordenCompra oc)
        {
            this.oc = oc;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "insertOrdenCompraResponse", WrapperNamespace = "http://services.ws.promass.buzone.com/", IsWrapped = true)]
    public partial class insertOrdenCompraResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://services.ws.promass.buzone.com/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiciosSalida.buzone.ordenescompra.resultado @return;

        public insertOrdenCompraResponse()
        {
        }

        public insertOrdenCompraResponse(ServiciosSalida.buzone.ordenescompra.resultado @return)
        {
            this.@return = @return;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OrdenCompraServiceChannel : ServiciosSalida.buzone.ordenescompra.OrdenCompraService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrdenCompraServiceClient : System.ServiceModel.ClientBase<ServiciosSalida.buzone.ordenescompra.OrdenCompraService>, ServiciosSalida.buzone.ordenescompra.OrdenCompraService
    {

        public OrdenCompraServiceClient()
        {
        }

        public OrdenCompraServiceClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public OrdenCompraServiceClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public OrdenCompraServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public OrdenCompraServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiciosSalida.buzone.ordenescompra.insertOrdenCompraResponse ServiciosSalida.buzone.ordenescompra.OrdenCompraService.insertOrdenCompra(ServiciosSalida.buzone.ordenescompra.insertOrdenCompraRequest request)
        {
            return base.Channel.insertOrdenCompra(request);
        }

        public ServiciosSalida.buzone.ordenescompra.resultado insertOrdenCompra(ServiciosSalida.buzone.ordenescompra.ordenCompra oc)
        {
            ServiciosSalida.buzone.ordenescompra.insertOrdenCompraRequest inValue = new ServiciosSalida.buzone.ordenescompra.insertOrdenCompraRequest();
            inValue.oc = oc;
            ServiciosSalida.buzone.ordenescompra.insertOrdenCompraResponse retVal = ((ServiciosSalida.buzone.ordenescompra.OrdenCompraService)(this)).insertOrdenCompra(inValue);
            return retVal.@return;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiciosSalida.buzone.ordenescompra.insertOrdenCompraResponse> ServiciosSalida.buzone.ordenescompra.OrdenCompraService.insertOrdenCompraAsync(ServiciosSalida.buzone.ordenescompra.insertOrdenCompraRequest request)
        {
            return base.Channel.insertOrdenCompraAsync(request);
        }

        public System.Threading.Tasks.Task<ServiciosSalida.buzone.ordenescompra.insertOrdenCompraResponse> insertOrdenCompraAsync(ServiciosSalida.buzone.ordenescompra.ordenCompra oc)
        {
            ServiciosSalida.buzone.ordenescompra.insertOrdenCompraRequest inValue = new ServiciosSalida.buzone.ordenescompra.insertOrdenCompraRequest();
            inValue.oc = oc;
            return ((ServiciosSalida.buzone.ordenescompra.OrdenCompraService)(this)).insertOrdenCompraAsync(inValue);
        }
    }
}
